### ISSUE TITLE
Add a LIVE server browser in bfportal.gg using gametools API

### ISSUE THREAD

**Issue by Matavatar** [battlefield-portal-community/bfportal.gg#110]
Add a LIVE server browser in bfportal.gg using gametools API. But only for experiences submitted on bfportal.gg. 

Flow : open exp page > click on "host exp server" button > check if experience is live with API > show server info (MATA NEED TO DO AN UI CONCEPT) 

This feature would be linked to the bfportal.gg bot and send a message to a specific channel

**Comment by p0lygun** [comment]
needs more discussion. will open again afterwords
