### ISSUE TITLE
Submit page - Interacting on category selection interchanges Experience URL and Code fields

### ISSUE THREAD

**Issue by RoflKartoffelDE** [battlefield-portal-community/bfportal.gg#18]
When first loading the submit page the order of items is as follows:
1. Category
2. Experience URL
3. Experience Code
4. ...

Once you select a category, the fields 2 and 3 will interchange.

**Comment by p0lygun** [comment]
oh, that is bad, I was trying something on local and these changes were not supposed to go through 
removing this https://github.com/battlefield-portal-community/bfportal.gg/blob/e70ee979c9e26ade70f5759487970d7ea088f9e6/bfportal/bfportal/static/js/bfportal.js#L6 should fix it
