### ISSUE TITLE
Add Cache headers for Cloud-flare to consume

### ISSUE THREAD

**Issue by p0lygun** [battlefield-portal-community/bfportal.gg#219]
Cloudflare provides free caching service to all users, but Currently, we are not making use of it on the Frontend, this leads to more requests at the server and more CPU cycles.

we can add caching to Frontend by making use of the `Cache-Control` http header. In this task, you will

- Identify all the points where we can use Cache
- Think of an efficient way to add headers for all points
- Set cache age accordingly

**Comment by zefanjajobse** [comment]
this is already implemented via cloudflare, all images use cloudflare cache and hit the cache correctly
@p0lygun 
<img width="445" alt="afbeelding" src="https://github.com/user-attachments/assets/ba21af34-9d3e-40a5-94b6-35fff3477bee">
